# Generated by Django 4.2.8 on 2023-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая новость', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug (URL)')),
                ('teaser', models.TextField(default='Тизер статьи', max_length=500, verbose_name='Тизер')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('text', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab commodi, consectetur dolores in iusto magni, nesciunt nulla possimus provident quis quos saepe? Animi cum distinctio dolore dolores et tempore, totam?', verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
