# Generated by Django 4.2.8 on 2023-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_news_date_news_creation_date_news_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.TextField(default='', max_length=100, verbose_name='Автор'),
        ),
    ]
