# Generated by Django 4.2.8 on 2023-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.FileField(default='', upload_to='news_images/', verbose_name='Изображение статьи'),
        ),
    ]
