# Generated by Django 4.2.8 on 2023-12-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.TextField(default='Аноним', max_length=100, verbose_name='Автор'),
        ),
    ]
