# Generated by Django 4.2.8 on 2023-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(default='/static/main/images/default-news-image.jpg', upload_to='news_images/', verbose_name='Изображение статьи'),
        ),
    ]
