# Generated by Django 4.2.8 on 2023-12-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(blank=True, default='', upload_to='news_images/', verbose_name='Изображение статьи'),
        ),
    ]
