# Generated by Django 4.2.8 on 2023-12-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_news_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-update_date', '-creation_date', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
