# Generated by Django 4.2.8 on 2023-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_news_options_news_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='moderated',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
