# Generated by Django 4.2.8 on 2024-01-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_news_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='news',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
